/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

/**
 *
 * @author roony
 */
public class AU extends javax.swing.JPanel {

     private String texto="Bienvenido a Burroswings, una aerolínea líder que se dedica a brindar experiencias de viaje excepcionales a nuestros pasajeros. Con un enfoque en la comodidad y la eficiencia, estamos comprometidos a proporcionar un servicio de reserva y gestión de vuelos de primera clase.\n" +
"\n" +"\n"+
"En Burroswings, comprendemos que cada viaje es una oportunidad para crear momentos inolvidables. Nuestra plataforma intuitiva y fácil de usar te permite reservar vuelos con total confianza y comodidad. Ya sea que estés planificando una escapada de negocios o unas merecidas vacaciones, estamos aquí para hacer que tu experiencia de vuelo sea fluida y sin complicaciones.\n" +
"\n" +
"Nuestro equipo está compuesto por profesionales apasionados que se esfuerzan por superar tus expectativas en cada etapa del viaje. Desde la elección de tu destino hasta el aterrizaje final, te ofrecemos un servicio de alta calidad respaldado por una dedicación inquebrantable hacia la satisfacción del cliente.\n" +
"\n" +
"Agradecemos la confianza que depositas en nosotros al elegir a Burroswings como tu compañía de confianza para tus viajes aéreos. Esperamos ser parte de tus aventuras y ayudarte a llegar a donde deseas, de la manera más conveniente y segura posible.\n" +
"\n" +
"¡Bienvenido a bordo de Burroswings!\n" +
"\n" +
"";
    
  
public String strHtml(String texto) {
    return "<html><p style='text-align: justify;'>" + texto + "</p></html>";
}
    
    public AU() {
        initComponents();
        lbAboutUs.setText(strHtml(texto));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAboutUs = new javax.swing.JLabel();

        lbAboutUs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(lbAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAboutUs;
    // End of variables declaration//GEN-END:variables
}
