/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

/**
 *
 * @author roony
 */
public class panelCancelarVuelo extends javax.swing.JPanel {

    private String textoCancelarVuelo = "¿Quieres cancelar tu vuelo? " + "<ol>"
        + "<li>Primero, dirígete al apartado de 'Rastrear Vuelo' presionando el botón 'Mi Vuelo'.</li>"
        + "<li>Una vez allí, necesitarás proporcionar tu clave de reserva, la cual se generó al finalizar tu registro de vuelo.</li>"
        + "<li>Para continuar, deberás realizar la confirmación de tu cancelación con tu clave de reserva.</li>"
        + "</ol>";

public String strHtmlCancelarVuelo(String textoCancelarVuelo) {
    return "<html><p style='text-align: justify;'>" + textoCancelarVuelo + "</p></html>";
}
    public panelCancelarVuelo() {
        initComponents();
        lbCancelarVuelo.setText(strHtmlCancelarVuelo(textoCancelarVuelo));
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCancelarVuelo = new javax.swing.JLabel();

        lbCancelarVuelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lbCancelarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCancelarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCancelarVuelo;
    // End of variables declaration//GEN-END:variables
}
