/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

/**
 *
 * @author roony
 */
public class panelCondiciones extends javax.swing.JPanel {

 
    private String textoCondicionesUso = "Bienvenido a nuestra aplicación de reservas de vuelos. Al utilizar esta aplicación, aceptas cumplir con los siguientes términos y condiciones:" + "<ul>"
        + "<li><strong>Aceptación de Términos:</strong> Al acceder y utilizar nuestra aplicación, aceptas estos términos en su totalidad.</li>"
        + "<li><strong>Uso Autorizado:</strong> Esta aplicación está destinada solo para el uso personal y no comercial. No debes utilizarla de manera que pueda dañar, deshabilitar o sobrecargar nuestros servicios.</li>"
        + "<li><strong>Registro de Cuenta:</strong> Al registrarte, eres responsable de mantener la confidencialidad de tu cuenta y contraseña. Notifícanos de inmediato sobre cualquier uso no autorizado de tu cuenta.</li>"
        + "<li><strong>Reservas y Pagos:</strong> Las reservas y pagos realizados a través de la aplicación están sujetos a nuestras políticas y condiciones de cancelación y reembolso.</li>"
        + "<li><strong>Modificaciones y Actualizaciones:</strong> Nos reservamos el derecho de modificar, suspender o interrumpir cualquier aspecto de la aplicación en cualquier momento, incluidos los términos de uso.</li>"
        + "<li><strong>Responsabilidad:</strong> No nos hacemos responsables de cualquier pérdida, daño o gasto resultante del uso de la aplicación o de la imposibilidad de acceder a ella.</li>"
        + "</ul>"
        + "Estas condiciones de uso constituyen un acuerdo completo entre el usuario y nosotros. Si no estás de acuerdo con estos términos, por favor, no utilices nuestra aplicación.";

public String strHtmlCondicionesUso(String textoCondicionesUso) {
    return "<html><p style='text-align: justify;'>" + textoCondicionesUso + "</p></html>";
}
    public panelCondiciones() {
        initComponents();
        lbCondiciones.setText(strHtmlCondicionesUso(textoCondicionesUso));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCondiciones = new javax.swing.JLabel();

        lbCondiciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lbCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCondiciones;
    // End of variables declaration//GEN-END:variables
}
